name: Test Flugel
on: 
  push:
    branches:
       - main
  pull_request:      
jobs:
  go-tests:
    name: Run Go Test Flugel
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v1
        with:
          go-version: x.x.x
      - uses: hashicorp/action-terraform@1
        with:
          terraform_version: x.x.x
      - name: Download Go Modules
        working-directory: /home/crobayo/test
        run: go mod download
      - name: Run Go Tests
        working-directory: /home/crobayo/test
        run: go test -v -tags=unit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}